#!/bin/sh

# cd to program's directory
ME=$0
DIR=$(dirname $ME)
cd $DIR

PY=$(which python2)
AGENT="$DIR/bin/xmlrpcserver.py"
AGENTPID="/tmp/gwman_agent.pid"

#/usr/local/bin/screen -d -m su arp -c 'python2 -m CGIHTTPServer'
#./bin/server.py &

start_agent () {
	if [ -f $AGENTPID ]; then
		echo "$AGENT already running with PID: $(cat $AGENTPID)"
	else
		$AGENT start
		STATUS=$?
	fi
	if [ "xxx$STATUS" == "xxx0" ]; then
		echo "$AGENT started sucefully."
	else
		echo "ERROR starting ${AGENT}."
	fi
}

stop_agent () {
	if [ ! -f $AGENTPID ]; then
		echo "$AGENT is not running, PID file not found on path: $AGENTPID"
	else
        $AGENT stop
        STATUS=$?
	fi
	if [ "xxx$STATUS" == "xxx0" ]; then
		echo "$AGENT stopped sucefully."
	else
		echo "ERROR stopping ${AGENT}."
	fi

}

status_agent () {
	if [ ! -f $AGENTPID ]; then
		echo "$AGENT is not running, PID file not found on path: $AGENTPID"
		return 1
	else
		PID=$(cat $AGENTPID)
		if kill -0 $PID; then
			echo "$AGENTPID already running with PID: $PID"
			return 0
		else
			echo "$AGENT is not running, but pidfile exists: $AGENTPID"
			return 1
		fi
	fi
}

case $1 in
start	)
	start_agent
;;
stop	)
	stop_agent
;;
restart	)
	stop_agent
	start_agent
;;
status	)
	status_agent
;;
*	)
	echo "$0 (start|stop|restart)";
;;
esac
