#!/bin/sh

# cd to program's directory
ME=$0
DIR=$(dirname $ME)
cd $DIR

PY=$(which python2)
BOTTLE="$DIR/bottle_server.py"
BOTTLEPID="/tmp/gwman_server.pid"

start_bottle () {
	if [ -f $BOTTLEPID ]; then
		echo "$BOTTLE already running with PID: $(cat $BOTTLEPID)"
		RES=0
	else
		$BOTTLE start
		RES=$?
	fi
	if [ "xxx0" == "xxx$RES" ]; then
		echo "$BOTTLE started sucefully"
	else
		echo "ERROR starting $BOTTLE"
	fi
}

stop_bottle () {
	if [ ! -f $BOTTLEPID ]; then
		echo "$BOTTLE is not running, PID file not found on path: $BOTTLEPID"
	else
        $BOTTLE stop
        RES=$?
        if [ "xxx0" == "xxx$RES" ]; then
            echo "$BOTTLE stopped sucefully"
        else
            echo "ERROR stopping $BOTTLE"
        fi
	fi
}

status_bottle () {
	if [ ! -f $BOTTLEPID ]; then
		echo "$BOTTLE is not running, PID file not found on path: $BOTTLEPID"
		return 1
	else
		PID=$(cat $BOTTLEPID)
		if kill -0 $PID; then
			echo "$BOTTLEPID already running with PID: $PID"
			return 0
		else
			echo "$BOTTLE is not running, but pidfile exists: $BOTTLEPID"
			return 1
		fi
	fi
}
case $1 in
start	)
	start_bottle
;;
stop	)
	stop_bottle
;;
restart	)
	stop_bottle
	start_bottle
;;
status	)
	status_bottle
;;
*	)
	echo "$0 (start|stop|restart)";
;;
esac
