#!/bin/sh

# cd to program's directory
ME=$0
DIR=$(dirname $ME)
cd $DIR

PY=$(which python2)
SERVER="$DIR/bin/xmlrpcserver.py"
SERVERPID="/tmp/gwman_server.pid"

#/usr/local/bin/screen -d -m su arp -c 'python2 -m CGIHTTPServer'
#./bin/server.py &

start_server () {
	if [ -f $SERVERPID ]; then
		echo "$SERVER already running with PID: $(cat $SERVERPID)"
	else
		$SERVER &
		PID=$!
	fi
	if [ "xxx" == "xxx$PID" ]; then
		echo "ERROR starting $SERVER"
	else
		echo $PID > $SERVERPID
		echo "$SERVER started sucefully. PID: $PID"
	fi
}

stop_server () {
	if [ ! -f $SERVERPID ]; then
		echo "$SERVER is not running, PID file not found on path: $SERVERPID"
	else
		PID=$(cat $SERVERPID)
		kill -TERM $PID
		echo "Killing process $PID..."
		while kill -0 $PID; do sleep 1; done
		echo "Done"
		rm -f $SERVERPID
	fi
}

status_server () {
	if [ ! -f $SERVERPID ]; then
		echo "$SERVER is not running, PID file not found on path: $SERVERPID"
		return 1
	else
		PID=$(cat $SERVERPID)
		if kill -0 $PID; then
			echo "$SERVERPID already running with PID: $PID"
			return 0
		else
			echo "$SERVER is not running, but pidfile exists: $SERVERPID"
			return 1
		fi
	fi
}

case $1 in
start	)
	start_server
;;
stop	)
	stop_server
;;
restart	)
	stop_server
	start_server
;;
status	)
	status_server
;;
*	)
	echo "$0 (start|stop|restart)";
;;
esac
